"""``TASKS.md``: the page a person opens.

Regenerated after every change, never edited by hand (its header says
so; edits belong in the task files). Open work comes first — active,
ready by urgency, waiting, blocked — then the same open tasks grouped
under the plan each belongs to, then what closed recently.

The path is ``board`` in ``.claude-hooks/tasks/config.toml``, default
``TASKS.md`` at the project root; ``board = ""`` turns it off.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from claude_hooks._atomic import write_text_atomic
from claude_hooks.tasks.render import ago, counts_line

log = logging.getLogger("claude_hooks.tasks.board")

DEFAULT_BOARD = "TASKS.md"
HEADER = ("<!-- Generated by claude-hooks from .claude-hooks/tasks/ — do not "
          "edit. Change a task with the task-* tools, claude-hooks-tasks, "
          "or by editing its file. -->")
_CLOSED_SHOWN = 15


def board_path(svc) -> Optional[Path]:
    rel = svc.dir.config().get("board", DEFAULT_BOARD)
    if not rel:
        return None
    return svc.dir.root / rel


def _link(svc, r: dict, board_dir: Path) -> str:
    sub = "archive/" if r.get("archived") else ""
    target = svc.dir.dir / f"{sub}{r['id']}.md"
    try:
        rel = target.relative_to(board_dir)
    except ValueError:
        rel = target
    return f"[{r['id']}]({rel.as_posix()})"


def _line(svc, r: dict, board_dir: Path) -> str:
    bits = [_link(svc, r, board_dir)]
    if r.get("priority") and r["priority"] != "M":
        bits.append(f"**{r['priority']}**")
    if r.get("area"):
        bits.append(f"`{r['area']}`")
    bits.append(r.get("title") or "")
    tail = []
    if r.get("open_depends"):
        tail.append("after " + ", ".join(r["open_depends"]))
    when = ago(r.get("updated") or "")
    if when:
        tail.append(when)
    return "- " + " ".join(bits) + (f" — {' · '.join(tail)}" if tail else "")


def render_board(svc, board: Optional[dict] = None,
                 board_dir: Optional[Path] = None) -> str:
    board = svc.board() if board is None else board
    board_dir = board_dir or svc.dir.root
    out = [HEADER, "", f"# Tasks — {svc.project}", "",
           f"{counts_line(board)} · prefix `{svc.dir.prefix}`", ""]
    for key, title in (("active", "Active"), ("ready", "Ready"),
                       ("waiting", "Waiting"), ("blocked", "Blocked")):
        rows = board.get(key) or []
        if not rows:
            continue
        out.append(f"## {title} ({len(rows)})\n")
        out.extend(_line(svc, r, board_dir) for r in rows)
        out.append("")
    open_rows = [r for k in ("active", "ready", "waiting", "blocked")
                 for r in board.get(k) or []]
    by_plan: dict[str, list] = {}
    for r in open_rows:
        if r.get("plan"):
            by_plan.setdefault(r["plan"], []).append(r)
    if by_plan:
        out.append("## By plan\n")
        for plan in sorted(by_plan):
            ids = ", ".join(_link(svc, r, board_dir) for r in sorted(
                by_plan[plan], key=lambda r: r.get("num", 0)))
            out.append(f"- `{plan}`: {ids}")
        out.append("")
    closed = (board.get("closed") or [])[:_CLOSED_SHOWN]
    if closed:
        total = len(board.get("closed") or [])
        out.append(f"## Recently closed ({len(closed)} of {total})\n")
        out.extend(_line(svc, r, board_dir) for r in closed)
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def write_board(svc, board: Optional[dict] = None) -> Optional[Path]:
    path = board_path(svc)
    if path is None or not svc.dir.exists:
        return None
    text = render_board(svc, board, path.parent)
    try:
        if path.read_text(encoding="utf-8") == text:
            return path                 # unchanged: leave the mtime alone
    except OSError:
        pass
    write_text_atomic(path, text)
    return path
